
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const migrationDatabaseUrl = process.env.DIRECT_URL || process.env.DATABASE_URL;

// The datasource URL is intentionally NOT resolved here.
//
// `env("DATABASE_URL")` is evaluated as soon as this config loads, which made
// every Prisma invocation — including `prisma generate`, which never opens a
// connection — fail with PrismaConfigEnvError when the variable was absent.
// That turned the `prebuild` hook into a hard build-time dependency on a
// database credential being present in the build environment.
//
// prisma/schema.prisma already declares `url = env("DATABASE_URL")`, which
// Prisma resolves lazily and only for commands that actually connect
// (migrate, db push, studio). Those still fail loudly when it is missing, and
// the application's own runtime validation in src/config/env.ts continues to
// require DATABASE_URL before the server will start.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // `generate` remains credential-free, while commands that actually connect
  // receive the direct database URL required by Prisma's config API.
  ...(migrationDatabaseUrl
    ? { datasource: { url: migrationDatabaseUrl } }
    : {}),
});
