import './setupEnv.js';
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  ExtractionError,
  activeProvider,
  extractTicket,
  mimeTypeForFilename,
} from '../src/services/extraction/extraction.service.js';

const fixturesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), 'fixtures');

/**
 * The parts of the extraction service that do not need a model.
 *
 * Everything a real call would tell us — whether a quantity was read correctly
 * off a creased photograph — is measured by scripts/extractionEval.ts against
 * hand-checked client documents, which cannot live in this repository. What is
 * testable here is the handling around the call: which files are accepted, and
 * whether a failure is one worth retrying.
 */

describe('document type handling', () => {
  test('accepts the formats drivers and suppliers actually send', () => {
    assert.equal(mimeTypeForFilename('ticket.jpg'), 'image/jpeg');
    assert.equal(mimeTypeForFilename('ticket.JPEG'), 'image/jpeg');
    assert.equal(mimeTypeForFilename('scan.png'), 'image/png');
    assert.equal(mimeTypeForFilename('invoice.pdf'), 'application/pdf');
  });

  test('refuses anything else, permanently', () => {
    // Retrying a .docx three more times over an hour helps nobody.
    for (const filename of ['notes.docx', 'sheet.xlsx', 'archive.zip', 'noextension']) {
      assert.throws(
        () => mimeTypeForFilename(filename),
        (error: unknown) =>
          error instanceof ExtractionError && error.retryable === false,
        `expected ${filename} to be refused permanently`
      );
    }
  });
});

describe('document size bounds', () => {
  test('an empty file fails without being sent anywhere', async () => {
    await assert.rejects(
      () => extractTicket(Buffer.alloc(0), 'image/jpeg', 'empty.jpg'),
      (error: unknown) => error instanceof ExtractionError && error.retryable === false
    );
  });

  test('an oversized file fails without being sent anywhere', async () => {
    // 21MB: past the 20MB ceiling, so it is refused before any upload cost.
    await assert.rejects(
      () => extractTicket(Buffer.alloc(21 * 1024 * 1024), 'image/jpeg', 'huge.jpg'),
      (error: unknown) => error instanceof ExtractionError && error.retryable === false
    );
  });
});

describe('provider configuration', () => {
  test('reports which model is in use', () => {
    // The eval script prints this, so a recorded result always names what it
    // measured rather than "the cheap one".
    const { name, modelId } = activeProvider();
    assert.equal(name, 'openai');
    assert.ok(modelId.length > 0);
  });
});

/**
 * One real call, run only when a genuine key is configured.
 *
 * `npm test` must never spend money or need network, so this skips by default.
 * Run it deliberately with a real OPENAI_API_KEY to confirm the wiring — the
 * request shape, the schema, the parse — actually works against the live API.
 */
const hasRealKey =
  !!process.env.OPENAI_API_KEY && process.env.OPENAI_API_KEY !== 'test-only-openai-key';
const fixture = path.join(fixturesDir, 'synthetic-ticket.png');

describe('live extraction', { skip: !hasRealKey || !fs.existsSync(fixture) }, () => {
  test('reads the synthetic ticket fixture end to end', async () => {
    const result = await extractTicket(fs.readFileSync(fixture), 'image/png', 'synthetic-ticket.png');

    // The fixture is generated by tests/fixtures/makeFixtures.ts with invented
    // supplier and PO values; no client document is in this repository.
    assert.equal(result.poNumber, '482913');
    assert.equal(result.quantity, 24.6);
    assert.ok(result.unit && /tonne/i.test(result.unit));
    assert.ok(result.supplierName && /millbrook/i.test(result.supplierName));
    assert.equal(result.ticketDate?.toISOString().slice(0, 10), '2026-08-13');
  });
});
